import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./ui/navigationBar";
import ClientProvider from "./clientProvider";
import Footer from "./ui/footer";
import AnnouncementBar from "./ui/announcementbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ClientProvider>
      <AnnouncementBar/>
       <NavigationBar />
        <main>
        {children}
        </main>
        <Footer/>
        </ClientProvider>
        </body>
    </html>
  );
}
