import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./clientProvider";
import Head from "next/head";
import AnnouncementBar from "./ui/announcementbar";
import NavigationBar from "./ui/navigationBar";
import Footer from "./ui/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mona+Sans:ital,wght@0,200..900;1,200..900&display=swap"
          rel="stylesheet"
        />
      </Head>
    <body className={inter.className}>
    <ClientProvider>
    <AnnouncementBar/>
    <NavigationBar />
        <main>
        {children}
        </main>
        <Footer/>
        </ClientProvider>
        </body>
    </html>
  );
}
